#!/usr/bin/env python3
import sys
import re

file_path = sys.argv[2]
if sys.argv[1] == '-c':
    # parse text file and return no. of bytes
    with open(file_path, 'rb') as file:
        content = file.read()

    print(len(content), file_path)

if sys.argv[1] == '-l':
    # parse text file and return no. of lines
    with open(file_path, 'r') as file:
        content = file.readlines()
    print(len(content), file_path)

if sys.argv[1] == '-w':
    # parse text file and return no. of words
    with open(file_path, 'r') as file:
        content = file.read()
        content = re.findall(r'\S+', content)
    print(len(content), file_path)