#!/usr/bin/env python3
import sys

file_path = sys.argv[2]
if sys.argv[1] == '-c':
    # parse text file and return no. of bytes
    with open(file_path, 'rb') as file:
        content = file.read()
print(len(content), file_path)